In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3]) # одномерный массив из 3 элементов

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [7]:
arr_zeros = np.zeros((2, 3)) # массив 2 на 3 из нулей

In [8]:
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr_ones = np.ones(7) # массив из единиц длинной 7

In [12]:
arr_ones

array([1., 1., 1., 1., 1., 1., 1.])

In [13]:
array_range = np.arange(0, 20, 2) # массив чисел с шагом 2

In [14]:
array_range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
print(array_range.shape)

(10,)


In [16]:
print(arr_zeros.shape)

(2, 3)


In [17]:
print(array_range.dtype)

int64


In [18]:
n = array_range[2] # Возьму элемент по индексу

In [19]:
n

np.int64(4)

In [21]:
slice_py = array_range[3:6] # взял с помощью среза элементы с индексами 3 4 5 

In [22]:
slice_py

array([ 6,  8, 10])

In [23]:
arr1 = np.array([11, 12, 1])

In [24]:
arr2 = np.array([17, 23, 5])

In [25]:
sum = arr1 + arr2 # поэлементное сложение массивов 

In [26]:
sum

array([28, 35,  6])

In [28]:
prod = arr1 * arr2 # поэлементное умножение массивов

In [29]:
prod

array([187, 276,   5])

In [30]:
a=np.arange(1,10,0.001) # показать, что выведется не весь массив в целях экономии места

In [31]:
a

array([1.   , 1.001, 1.002, ..., 9.997, 9.998, 9.999], shape=(9000,))

In [32]:
a + 1

array([ 2.   ,  2.001,  2.002, ..., 10.997, 10.998, 10.999], shape=(9000,))

In [34]:
arr1 + 1

array([12, 13,  2])

In [35]:
arr1 ** 2

array([121, 144,   1])

In [37]:
arr3 = np.arange(1,21,1)

In [38]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
arr3 ** 2 # массив квадратов от 1 до 20

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [40]:
arr3.max()

np.int64(20)

In [41]:
arr3.min()

np.int64(1)

In [42]:
grade = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [43]:
grade.mean() # среднее арифметическое из значений массива

np.float64(5.5)

In [44]:
print("Нормализованные оценки из массива: ", (grade - grade.min()) / (grade.max() - grade.min()))

Нормализованные оценки из массива:  [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
