In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3]) # одномерный массив из 3 элементов

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [7]:
arr_zeros = np.zeros((2, 3)) # массив 2 на 3 из нулей

In [8]:
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr_ones = np.ones(7) # массив из единиц длинной 7

In [12]:
arr_ones

array([1., 1., 1., 1., 1., 1., 1.])

In [13]:
array_range = np.arange(0, 20, 2) # массив чисел с шагом 2

In [14]:
array_range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
print(array_range.shape)

(10,)


In [16]:
print(arr_zeros.shape)

(2, 3)


In [17]:
print(array_range.dtype)

int64


In [18]:
n = array_range[2] # Возьму элемент по индексу

In [19]:
n

np.int64(4)

In [21]:
slice_py = array_range[3:6] # взял с помощью среза элементы с индексами 3 4 5 

In [22]:
slice_py

array([ 6,  8, 10])

In [23]:
arr1 = np.array([11, 12, 1])

In [24]:
arr2 = np.array([17, 23, 5])

In [25]:
sum = arr1 + arr2 # поэлементное сложение массивов 

In [26]:
sum

array([28, 35,  6])

In [28]:
prod = arr1 * arr2 # поэлементное умножение массивов

In [29]:
prod

array([187, 276,   5])

In [30]:
a=np.arange(1,10,0.001) # показать, что выведется не весь массив в целях экономии места

In [31]:
a

array([1.   , 1.001, 1.002, ..., 9.997, 9.998, 9.999], shape=(9000,))

In [32]:
a + 1

array([ 2.   ,  2.001,  2.002, ..., 10.997, 10.998, 10.999], shape=(9000,))

In [34]:
arr1 + 1

array([12, 13,  2])

In [35]:
arr1 ** 2

array([121, 144,   1])

In [37]:
arr3 = np.arange(1,21,1)

In [38]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
arr3 ** 2 # массив квадратов от 1 до 20

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [40]:
arr3.max()

np.int64(20)

In [41]:
arr3.min()

np.int64(1)

In [42]:
grade = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [43]:
grade.mean() # среднее арифметическое из значений массива

np.float64(5.5)

In [44]:
print("Нормализованные оценки из массива: ", (grade - grade.min()) / (grade.max() - grade.min()))

Нормализованные оценки из массива:  [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [3]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
print(f"Исходный массив: {a}")

Исходный массив: [ 1  2  3  4  5  6  7  8  9 10]


In [10]:
a[-1] # последний элемент

np.int64(10)

In [11]:
a[0] # первый элемент массива

np.int64(1)

In [12]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [13]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a2[0, 0] # посмотрим по индексу первый элемент 

np.int64(1)

In [34]:
a2[2, 1]

np.int64(8)

In [32]:
a[-1] = 66 # поменял по индексу последний элемент массива

In [19]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 66])

In [24]:
a2[2, 0]

np.int64(7)

In [31]:
a2[2, 0] = -4 # поменял элемент по индексу (2,0)  

In [26]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [-4,  8,  9]])

In [30]:
a_slice = np.arange(10) ** 3 # кубы чисел 0-9

In [29]:
a_slice

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [35]:
# примеры срезов

In [37]:
a_slice[2:5] # срез элементов по индексам 2-4

array([ 8, 27, 64])

In [39]:
a_slice[:3] # срез первых трех элементов

array([0, 1, 8])

In [41]:
a_slice[4:] # от элемента с индексом 4 и до конца

array([ 64, 125, 216, 343, 512, 729])

In [43]:
a_slice[::-1] # массив в обратном порядке

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [47]:
a_slice[1:8:2] # срез с 1 элемента по индексу с шагом 2

array([  1,  27, 125, 343])

In [49]:
a_slice[::2] # каждый второй элемент 

array([  0,   8,  64, 216, 512])

In [50]:
c = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

In [51]:
c 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
c[0:3, :] # вывел строки 0-2 и все столбцы

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
c[2:4, 0:3] # строки 2-3, столбцы 0-2

array([[ 9, 10, 11],
       [13, 14, 15]])

In [58]:
dd = np.arange(7)

In [59]:
dd

array([0, 1, 2, 3, 4, 5, 6])

In [63]:
dd[0:3] = [72, 2005, 28] # с помощью среза изменил элементы 0-3

In [61]:
dd

array([  72, 2005,   28,    3,    4,    5,    6])